#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pygobuildinfo
import glob
import sys
import json

for arg  in sys.argv[1:]:
    for file in glob.glob(arg):
        result = pyGoBuildInfo.get_go_build_info(file)
        print(json.dumps(result,indent=4))

