#!/usr/bin/env python
# -*- coding: utf-8 -*-
from pygobuildinfo import get_go_build_info
import glob
import sys
import json

for arg  in sys.argv[1:]:
    for file in glob.glob(arg):
        result = get_go_build_info(file)
        print(json.dumps(result,indent=4))

